name: Clasp Action
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
  # PUSH
    - uses: daikikatsuragawa/clasp-action@v1.1.0
      with:
        accessToken: ${{ secrets.ACCESSTOKEN }}
        idToken: ${{ secrets.IDTOKEN }}
        refreshToken: ${{ secrets.REFRESHTOKEN }}
        clientId: ${{ secrets.CLIENTID }}
        clientSecret: ${{ secrets.CLIENTSECRET }}
        scriptId: ${{ secrets.SCRIPTID }}
        rootDir: ${{ secrets.ROOTDIR }}
        command: 'push'
        description: 'Sample description'
        deployId: ${{ secrets.DEPLOYID }}
    - name: ruta
      run: echo "::pwd"    

